import Head from "next/head"
import Header from "./Header"

const Layout = ({ children }) => {
  return (
    <div className="overflow-x-hidden scroll-smooth relative bg-white dark:from-black dark:to-neutral-900 dark:bg-gradient-to-b transition-colors">
      <Head>
        <title>Erickrv Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="md:pt-10 pt-24">{children}</main>
    </div>
  )
}

export default Layout
