import Head from 'next/head'
import Header from './Header'


const Layout = ({children}) => {


  return (
    <div id='scrol' className='h-screen overflow-hidden overflow-y-scroll scroll-smooth relative bg-white dark:bg-neutral-800 transition-colors' >
        <Head>
            <title>Erickrv Portafolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
        
        <Header />

         <main className='md:pt-10 pt-24'>
            {children}
         </main>
    </div>
  )
}

export default Layout